version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/learning_platform
      - PYTHONPATH=/app
    depends_on:
      - postgres
    networks:
      - learning-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  postgres:
    image: postgres:15-alpine
    container_name: learning-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=learning_platform
    ports:
      - "5433:5432"  # 기존 5432와 충돌 방지
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - learning-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  learning-network:
    driver: bridge

volumes:
  postgres_data:
